--this source code was auto-generated by xls2lua.exe, do not modify it

local VAR_TO_TRANSL_KEY_DATA=
{
	EVar = 
	{
		translV_key_s=1,--"翻译键名"
		translN_key_s=2,--"翻译键名"
	},
	["bldg_size_n"]={"ATRBBuildingArea","ATRBBuildingAreaN"},
	["cult_pt_n"]={"ATRBCivilization","ATRBNoUnitN"},
	["ele_regen_rate_n"]={"ATRBChargeV","ATRBChargeN"},
	["max_ele_cap_n"]={"ATRBCapV","ATRBCapN"},
	["max_item_cap_n"]={"ATRBCapacityV","ATRBCapacityN"},
	["affact_rng_n"]={"ATRBRangeV","ATRBRangeN"},
	["ssp_vol_n"]={"ATRBBerthV","ATRBBerthN"},
	["repr_spd_coeff_n"]={"ATRBRepairV","ATRBRepairN"},
	["prod_spd_coeff_n"]={"ATRBProV","ATRBRepairN"},
	["temp_cap_n"]={"ATRBCollectV","ATRBNoUnitN"},
	["mining_spd_coeff_n"]={"ATRBMiningV","ATRBm³/h"},
	["max_cap_n"]={"ATRBCollectV","ATRBNoUnitN"},
	["refine_spd_coeff_n"]={"ATRBRRefiningV","ATRBm³/h"},
	["max_refine_qty_n"]={"ATRBCollectV","ATRBNoUnitN"},
}
return VAR_TO_TRANSL_KEY_DATA
