--this source code was auto-generated by xls2lua.exe, do not modify it

local TASK_ONLINE_TIME_DATA=
{
	EVar = 
	{
		cd_time_n=1,--"冷却时间"
		qty_limit_n=2,--"次数限制"
		star_dust_n=3,--"星尘数"
		tech_point_n=4,--"科技点数"
	},
	[1]={180,80,300,20},
}
return TASK_ONLINE_TIME_DATA
