--this source code was auto-generated by xls2lua.exe, do not modify it

local USER_INIT_ITEM_DATA=
{
	EVar = 
	{
		item_qty_n=1,--"物品数量"
	},
	[220000101]={1000},
	[220000201]={600},
	[210000001]={300},
	[210000002]={180},
	[21110401]={1},
	[21120401]={1},
	[21130101]={1},
}
return USER_INIT_ITEM_DATA
