-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local db_pb = require("db_pb")
local common_pb = require("common_pb")
local buildingPort_pb = require("buildingPort_pb")
local db_pb = require("db_pb")
local common_pb = require("common_pb")
local node_pb = require("node_pb")
local db_pb = require("db_pb")
module('business_pb')


local pb = {}
pb.SPEEDUPTYPE = protobuf.EnumDescriptor();
pb.SPEEDUPTYPEFLEET_MOVE_ENUM = protobuf.EnumValueDescriptor();
pb.SPEEDUPTYPEBUILDING_LEVEL_UP_ENUM = protobuf.EnumValueDescriptor();
pb.TCSSPEEDUP = protobuf.Descriptor();
pb.TCSSPEEDUPID_FIELD = protobuf.FieldDescriptor();
pb.TCSSPEEDUPTYPE_FIELD = protobuf.FieldDescriptor();
pb.TCSSPEEDUPITEMID_FIELD = protobuf.FieldDescriptor();
pb.TSCSPEEDUP = protobuf.Descriptor();
pb.TSCSPEEDUPID_FIELD = protobuf.FieldDescriptor();
pb.TSCSPEEDUPTYPE_FIELD = protobuf.FieldDescriptor();
pb.TSCSPEEDUPITEMID_FIELD = protobuf.FieldDescriptor();
pb.TSCSPEEDUPENDTIME_FIELD = protobuf.FieldDescriptor();

pb.SPEEDUPTYPEFLEET_MOVE_ENUM.name = "FLEET_MOVE"
pb.SPEEDUPTYPEFLEET_MOVE_ENUM.index = 0
pb.SPEEDUPTYPEFLEET_MOVE_ENUM.number = 1
pb.SPEEDUPTYPEBUILDING_LEVEL_UP_ENUM.name = "BUILDING_LEVEL_UP"
pb.SPEEDUPTYPEBUILDING_LEVEL_UP_ENUM.index = 1
pb.SPEEDUPTYPEBUILDING_LEVEL_UP_ENUM.number = 2
pb.SPEEDUPTYPE.name = "SpeedUpType"
pb.SPEEDUPTYPE.full_name = ".com.nkm.common.proto.client.SpeedUpType"
pb.SPEEDUPTYPE.values = {pb.SPEEDUPTYPEFLEET_MOVE_ENUM,pb.SPEEDUPTYPEBUILDING_LEVEL_UP_ENUM}
pb.TCSSPEEDUPID_FIELD.name = "id"
pb.TCSSPEEDUPID_FIELD.full_name = ".com.nkm.common.proto.client.TCSSpeedUp.id"
pb.TCSSPEEDUPID_FIELD.number = 1
pb.TCSSPEEDUPID_FIELD.index = 0
pb.TCSSPEEDUPID_FIELD.label = 2
pb.TCSSPEEDUPID_FIELD.has_default_value = false
pb.TCSSPEEDUPID_FIELD.default_value = 0
pb.TCSSPEEDUPID_FIELD.type = 3
pb.TCSSPEEDUPID_FIELD.cpp_type = 2

pb.TCSSPEEDUPTYPE_FIELD.name = "type"
pb.TCSSPEEDUPTYPE_FIELD.full_name = ".com.nkm.common.proto.client.TCSSpeedUp.type"
pb.TCSSPEEDUPTYPE_FIELD.number = 2
pb.TCSSPEEDUPTYPE_FIELD.index = 1
pb.TCSSPEEDUPTYPE_FIELD.label = 2
pb.TCSSPEEDUPTYPE_FIELD.has_default_value = false
pb.TCSSPEEDUPTYPE_FIELD.default_value = 0
pb.TCSSPEEDUPTYPE_FIELD.type = 5
pb.TCSSPEEDUPTYPE_FIELD.cpp_type = 1

pb.TCSSPEEDUPITEMID_FIELD.name = "itemId"
pb.TCSSPEEDUPITEMID_FIELD.full_name = ".com.nkm.common.proto.client.TCSSpeedUp.itemId"
pb.TCSSPEEDUPITEMID_FIELD.number = 3
pb.TCSSPEEDUPITEMID_FIELD.index = 2
pb.TCSSPEEDUPITEMID_FIELD.label = 1
pb.TCSSPEEDUPITEMID_FIELD.has_default_value = false
pb.TCSSPEEDUPITEMID_FIELD.default_value = 0
pb.TCSSPEEDUPITEMID_FIELD.type = 5
pb.TCSSPEEDUPITEMID_FIELD.cpp_type = 1

pb.TCSSPEEDUP.name = "TCSSpeedUp"
pb.TCSSPEEDUP.full_name = ".com.nkm.common.proto.client.TCSSpeedUp"
pb.TCSSPEEDUP.nested_types = {}
pb.TCSSPEEDUP.enum_types = {}
pb.TCSSPEEDUP.fields = {pb.TCSSPEEDUPID_FIELD, pb.TCSSPEEDUPTYPE_FIELD, pb.TCSSPEEDUPITEMID_FIELD}
pb.TCSSPEEDUP.is_extendable = false
pb.TCSSPEEDUP.extensions = {}
pb.TSCSPEEDUPID_FIELD.name = "id"
pb.TSCSPEEDUPID_FIELD.full_name = ".com.nkm.common.proto.client.TSCSpeedUp.id"
pb.TSCSPEEDUPID_FIELD.number = 1
pb.TSCSPEEDUPID_FIELD.index = 0
pb.TSCSPEEDUPID_FIELD.label = 2
pb.TSCSPEEDUPID_FIELD.has_default_value = false
pb.TSCSPEEDUPID_FIELD.default_value = 0
pb.TSCSPEEDUPID_FIELD.type = 3
pb.TSCSPEEDUPID_FIELD.cpp_type = 2

pb.TSCSPEEDUPTYPE_FIELD.name = "type"
pb.TSCSPEEDUPTYPE_FIELD.full_name = ".com.nkm.common.proto.client.TSCSpeedUp.type"
pb.TSCSPEEDUPTYPE_FIELD.number = 2
pb.TSCSPEEDUPTYPE_FIELD.index = 1
pb.TSCSPEEDUPTYPE_FIELD.label = 2
pb.TSCSPEEDUPTYPE_FIELD.has_default_value = false
pb.TSCSPEEDUPTYPE_FIELD.default_value = 0
pb.TSCSPEEDUPTYPE_FIELD.type = 5
pb.TSCSPEEDUPTYPE_FIELD.cpp_type = 1

pb.TSCSPEEDUPITEMID_FIELD.name = "itemId"
pb.TSCSPEEDUPITEMID_FIELD.full_name = ".com.nkm.common.proto.client.TSCSpeedUp.itemId"
pb.TSCSPEEDUPITEMID_FIELD.number = 3
pb.TSCSPEEDUPITEMID_FIELD.index = 2
pb.TSCSPEEDUPITEMID_FIELD.label = 1
pb.TSCSPEEDUPITEMID_FIELD.has_default_value = false
pb.TSCSPEEDUPITEMID_FIELD.default_value = 0
pb.TSCSPEEDUPITEMID_FIELD.type = 5
pb.TSCSPEEDUPITEMID_FIELD.cpp_type = 1

pb.TSCSPEEDUPENDTIME_FIELD.name = "endTime"
pb.TSCSPEEDUPENDTIME_FIELD.full_name = ".com.nkm.common.proto.client.TSCSpeedUp.endTime"
pb.TSCSPEEDUPENDTIME_FIELD.number = 4
pb.TSCSPEEDUPENDTIME_FIELD.index = 3
pb.TSCSPEEDUPENDTIME_FIELD.label = 2
pb.TSCSPEEDUPENDTIME_FIELD.has_default_value = false
pb.TSCSPEEDUPENDTIME_FIELD.default_value = 0
pb.TSCSPEEDUPENDTIME_FIELD.type = 3
pb.TSCSPEEDUPENDTIME_FIELD.cpp_type = 2

pb.TSCSPEEDUP.name = "TSCSpeedUp"
pb.TSCSPEEDUP.full_name = ".com.nkm.common.proto.client.TSCSpeedUp"
pb.TSCSPEEDUP.nested_types = {}
pb.TSCSPEEDUP.enum_types = {}
pb.TSCSPEEDUP.fields = {pb.TSCSPEEDUPID_FIELD, pb.TSCSPEEDUPTYPE_FIELD, pb.TSCSPEEDUPITEMID_FIELD, pb.TSCSPEEDUPENDTIME_FIELD}
pb.TSCSPEEDUP.is_extendable = false
pb.TSCSPEEDUP.extensions = {}

BUILDING_LEVEL_UP = 2
FLEET_MOVE = 1
TCSSpeedUp = protobuf.Message(pb.TCSSPEEDUP)
TSCSpeedUp = protobuf.Message(pb.TSCSPEEDUP)

