//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NLanguageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NLanguage), typeof(System.Object));
		L.RegFunction("GetCurrentLanguage", GetCurrentLanguage);
		L.RegFunction("New", _CreateNLanguage);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNLanguage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				NLanguage obj = new NLanguage();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NLanguage.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurrentLanguage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			int o = NLanguage.GetCurrentLanguage();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

