--this source code was auto-generated by xls2lua.exe, do not modify it

local GUIDE_DATA=
{
	EVar = 
	{
		intro_point_n=1,--"条件点"
		condition_s=2,--"条件"
		prev_id_n=3,--"前置引导ID"
		complete_ids_s=4,--"完成引导ID"
		show_type_n=5,--"显示类型"
		player_rank_n=6,--"角色等级"
		page_name_s=7,--"页面名称"
		hand_param_s=8,--"参数"
		text_key_s=9,--"文本Key"
		picture_name_s=10,--"图片名称"
	},
	[1]={1,"",0,"1",1,1,"BuildingListPanel","","","a"},
	[2]={1,"1#2",1,"",3,1,"BuildingListPanel","0#0#1","","b"},
	[3]={1,"1#3",2,"2#3",5,1,"BuildingListPanel","","",""},
}
return GUIDE_DATA
