--this source code was auto-generated by xls2lua.exe, do not modify it

local ITEM_MIN_DATA=
{
	EVar = 
	{
		transl_table_name_s=1,--"翻译表名"
		min_name_s=2,--"矿物名称"
		icon_name_s=3,--"图标名称"
		small_icon_name_s=4,--"小图标名称"
		item_lvl_n=5,--"物品等级"
		desc_s=6,--"描述"
		multiplier_n=7,--"倍率"
		time_cost_n=8,--"消耗时间;(秒)"
		ele_cost_n=9,--"消耗电力"
		cost_qty_n=10,--"消耗数量"
		result_id_n=11,--"结果ID"
		stor_unit_n=12,--"储存体积;占用;(立方米)"
	},
	[210000001]={"ItemName","ResZYS","UITexture/ItemMin/210000001.png","c1ic41",1,"ResZYSDtl",5,1,0,1,220000101,1},
	[210000002]={"ItemName","ResJS","UITexture/ItemMin/210000002.png","c1ic39",1,"ResJSDtl",3,2,0,1,220000201,1},
	[210000003]={"ItemName","ResYT","UITexture/ItemMin/210000003.png","c1ic40",1,"ResYTDtl",2,3,0,1,220000301,1},
	[210000004]={"ItemName","ResJT","UITexture/ItemMin/210000004.png","c1ic38",1,"ResJTDtl",1,6,0,1,220000401,1},
}
return ITEM_MIN_DATA
