--this source code was auto-generated by xls2lua.exe, do not modify it

local REGION_NAME_DATA=
{
	EVar = 
	{
		region_name_s=1,--"星域名"
	},
	[1]={"CYG"},
	[2]={"AQL"},
	[3]={"VUL"},
	[4]={"SGE"},
	[5]={"OPH"},
	[6]={"SCT"},
	[7]={"SGR"},
	[8]={"SCO"},
	[9]={"ARA"},
	[10]={"NOR"},
	[11]={"LUP"},
	[12]={"TRA"},
	[13]={"CIR"},
	[14]={"MUS"},
	[15]={"CRU"},
	[16]={"VEL"},
	[17]={"PUP"},
	[18]={"MON"},
	[19]={"ORI"},
	[20]={"TAU"},
	[21]={"GEM"},
	[22]={"AUR"},
	[23]={"PER"},
	[24]={"CAS"},
	[25]={"LAC"},
}
return REGION_NAME_DATA
