//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NLoadSceneWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NLoadScene), typeof(System.Object));
		L.RegFunction("LoadSceneAsync", LoadSceneAsync);
		L.RegFunction("New", _CreateNLoadScene);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ActiveSceneName", get_ActiveSceneName, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNLoadScene(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				NLoadScene obj = new NLoadScene();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NLoadScene.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSceneAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			UnityEngine.AsyncOperation o = NLoadScene.LoadSceneAsync(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ActiveSceneName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NLoadScene.ActiveSceneName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

