--this source code was auto-generated by xls2lua.exe, do not modify it

local MINERAL_FIN_DATA=
{
	EVar = 
	{
		produce_rate_n=1,--"产出速度;(个/小时)"
	},
	[1]={360},
	[2]={450},
	[3]={540},
	[4]={720},
	[5]={900},
	[6]={1260},
	[7]={1800},
	[8]={2520},
	[9]={3420},
	[10]={4500},
}
return MINERAL_FIN_DATA
