-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('bundleInfo_pb')


local pb = {}
pb.BUNDLEINFO = protobuf.Descriptor();
pb.BUNDLEINFOPATH_FIELD = protobuf.FieldDescriptor();
pb.BUNDLEINFOGUID_FIELD = protobuf.FieldDescriptor();
pb.BUNDLEINFOMD5_FIELD = protobuf.FieldDescriptor();
pb.BUNDLEINFOTABLE = protobuf.Descriptor();
pb.BUNDLEINFOTABLEDATA_FIELD = protobuf.FieldDescriptor();

pb.BUNDLEINFOPATH_FIELD.name = "path"
pb.BUNDLEINFOPATH_FIELD.full_name = ".com.nkm.common.proto.client.BundleInfo.path"
pb.BUNDLEINFOPATH_FIELD.number = 1
pb.BUNDLEINFOPATH_FIELD.index = 0
pb.BUNDLEINFOPATH_FIELD.label = 1
pb.BUNDLEINFOPATH_FIELD.has_default_value = false
pb.BUNDLEINFOPATH_FIELD.default_value = ""
pb.BUNDLEINFOPATH_FIELD.type = 9
pb.BUNDLEINFOPATH_FIELD.cpp_type = 9

pb.BUNDLEINFOGUID_FIELD.name = "guid"
pb.BUNDLEINFOGUID_FIELD.full_name = ".com.nkm.common.proto.client.BundleInfo.guid"
pb.BUNDLEINFOGUID_FIELD.number = 2
pb.BUNDLEINFOGUID_FIELD.index = 1
pb.BUNDLEINFOGUID_FIELD.label = 1
pb.BUNDLEINFOGUID_FIELD.has_default_value = false
pb.BUNDLEINFOGUID_FIELD.default_value = ""
pb.BUNDLEINFOGUID_FIELD.type = 9
pb.BUNDLEINFOGUID_FIELD.cpp_type = 9

pb.BUNDLEINFOMD5_FIELD.name = "md5"
pb.BUNDLEINFOMD5_FIELD.full_name = ".com.nkm.common.proto.client.BundleInfo.md5"
pb.BUNDLEINFOMD5_FIELD.number = 3
pb.BUNDLEINFOMD5_FIELD.index = 2
pb.BUNDLEINFOMD5_FIELD.label = 1
pb.BUNDLEINFOMD5_FIELD.has_default_value = false
pb.BUNDLEINFOMD5_FIELD.default_value = ""
pb.BUNDLEINFOMD5_FIELD.type = 9
pb.BUNDLEINFOMD5_FIELD.cpp_type = 9

pb.BUNDLEINFO.name = "BundleInfo"
pb.BUNDLEINFO.full_name = ".com.nkm.common.proto.client.BundleInfo"
pb.BUNDLEINFO.nested_types = {}
pb.BUNDLEINFO.enum_types = {}
pb.BUNDLEINFO.fields = {pb.BUNDLEINFOPATH_FIELD, pb.BUNDLEINFOGUID_FIELD, pb.BUNDLEINFOMD5_FIELD}
pb.BUNDLEINFO.is_extendable = false
pb.BUNDLEINFO.extensions = {}
pb.BUNDLEINFOTABLEDATA_FIELD.name = "data"
pb.BUNDLEINFOTABLEDATA_FIELD.full_name = ".com.nkm.common.proto.client.BundleInfoTable.data"
pb.BUNDLEINFOTABLEDATA_FIELD.number = 1
pb.BUNDLEINFOTABLEDATA_FIELD.index = 0
pb.BUNDLEINFOTABLEDATA_FIELD.label = 3
pb.BUNDLEINFOTABLEDATA_FIELD.has_default_value = false
pb.BUNDLEINFOTABLEDATA_FIELD.default_value = {}
pb.BUNDLEINFOTABLEDATA_FIELD.message_type = pb.BUNDLEINFO
pb.BUNDLEINFOTABLEDATA_FIELD.type = 11
pb.BUNDLEINFOTABLEDATA_FIELD.cpp_type = 10

pb.BUNDLEINFOTABLE.name = "BundleInfoTable"
pb.BUNDLEINFOTABLE.full_name = ".com.nkm.common.proto.client.BundleInfoTable"
pb.BUNDLEINFOTABLE.nested_types = {}
pb.BUNDLEINFOTABLE.enum_types = {}
pb.BUNDLEINFOTABLE.fields = {pb.BUNDLEINFOTABLEDATA_FIELD}
pb.BUNDLEINFOTABLE.is_extendable = false
pb.BUNDLEINFOTABLE.extensions = {}

BundleInfo = protobuf.Message(pb.BUNDLEINFO)
BundleInfoTable = protobuf.Message(pb.BUNDLEINFOTABLE)

