-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local db_pb = require("db_pb")
local common_pb = require("common_pb")
local buildingPort_pb = require("buildingPort_pb")
local db_pb = require("db_pb")
local common_pb = require("common_pb")
local node_pb = require("node_pb")
local db_pb = require("db_pb")
module('gm_pb')


local pb = {}
pb.TCSGM = protobuf.Descriptor();
pb.TCSGMGMCMD_FIELD = protobuf.FieldDescriptor();
pb.TSCGM = protobuf.Descriptor();
pb.TSCGMRES_FIELD = protobuf.FieldDescriptor();

pb.TCSGMGMCMD_FIELD.name = "gmCmd"
pb.TCSGMGMCMD_FIELD.full_name = ".com.nkm.common.proto.client.TCSGm.gmCmd"
pb.TCSGMGMCMD_FIELD.number = 1
pb.TCSGMGMCMD_FIELD.index = 0
pb.TCSGMGMCMD_FIELD.label = 1
pb.TCSGMGMCMD_FIELD.has_default_value = false
pb.TCSGMGMCMD_FIELD.default_value = ""
pb.TCSGMGMCMD_FIELD.type = 9
pb.TCSGMGMCMD_FIELD.cpp_type = 9

pb.TCSGM.name = "TCSGm"
pb.TCSGM.full_name = ".com.nkm.common.proto.client.TCSGm"
pb.TCSGM.nested_types = {}
pb.TCSGM.enum_types = {}
pb.TCSGM.fields = {pb.TCSGMGMCMD_FIELD}
pb.TCSGM.is_extendable = false
pb.TCSGM.extensions = {}
pb.TSCGMRES_FIELD.name = "res"
pb.TSCGMRES_FIELD.full_name = ".com.nkm.common.proto.client.TSCGm.res"
pb.TSCGMRES_FIELD.number = 1
pb.TSCGMRES_FIELD.index = 0
pb.TSCGMRES_FIELD.label = 1
pb.TSCGMRES_FIELD.has_default_value = false
pb.TSCGMRES_FIELD.default_value = ""
pb.TSCGMRES_FIELD.type = 9
pb.TSCGMRES_FIELD.cpp_type = 9

pb.TSCGM.name = "TSCGm"
pb.TSCGM.full_name = ".com.nkm.common.proto.client.TSCGm"
pb.TSCGM.nested_types = {}
pb.TSCGM.enum_types = {}
pb.TSCGM.fields = {pb.TSCGMRES_FIELD}
pb.TSCGM.is_extendable = false
pb.TSCGM.extensions = {}

TCSGm = protobuf.Message(pb.TCSGM)
TSCGm = protobuf.Message(pb.TSCGM)

