-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local login_pb = require("login_pb")
module('user_pb')


local pb = {}
pb.TCSTASKONLINECOLLECT = protobuf.Descriptor();
pb.TSCTASKONLINECOLLECT = protobuf.Descriptor();
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD = protobuf.FieldDescriptor();
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD = protobuf.FieldDescriptor();
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD = protobuf.FieldDescriptor();
pb.TCSGUIDE = protobuf.Descriptor();
pb.TCSGUIDEGUIDE_FIELD = protobuf.FieldDescriptor();
pb.TCSUSERLEVELUP = protobuf.Descriptor();
pb.TSCUSERLEVELUP = protobuf.Descriptor();
pb.TSCUSERLEVELUPLEVEL_FIELD = protobuf.FieldDescriptor();

pb.TCSTASKONLINECOLLECT.name = "TCSTaskOnlineCollect"
pb.TCSTASKONLINECOLLECT.full_name = ".com.nkm.common.proto.client.TCSTaskOnlineCollect"
pb.TCSTASKONLINECOLLECT.nested_types = {}
pb.TCSTASKONLINECOLLECT.enum_types = {}
pb.TCSTASKONLINECOLLECT.fields = {}
pb.TCSTASKONLINECOLLECT.is_extendable = false
pb.TCSTASKONLINECOLLECT.extensions = {}
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.name = "taskOnline"
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.full_name = ".com.nkm.common.proto.client.TSCTaskOnlineCollect.taskOnline"
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.number = 1
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.index = 0
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.label = 1
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.has_default_value = false
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.default_value = nil
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.message_type = login_pb.TaskOnline
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.type = 11
pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD.cpp_type = 10

pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.name = "techPoint"
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.full_name = ".com.nkm.common.proto.client.TSCTaskOnlineCollect.techPoint"
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.number = 2
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.index = 1
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.label = 1
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.has_default_value = false
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.default_value = 0
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.type = 5
pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD.cpp_type = 1

pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.name = "starDust"
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.full_name = ".com.nkm.common.proto.client.TSCTaskOnlineCollect.starDust"
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.number = 3
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.index = 2
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.label = 1
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.has_default_value = false
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.default_value = 0
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.type = 5
pb.TSCTASKONLINECOLLECTSTARDUST_FIELD.cpp_type = 1

pb.TSCTASKONLINECOLLECT.name = "TSCTaskOnlineCollect"
pb.TSCTASKONLINECOLLECT.full_name = ".com.nkm.common.proto.client.TSCTaskOnlineCollect"
pb.TSCTASKONLINECOLLECT.nested_types = {}
pb.TSCTASKONLINECOLLECT.enum_types = {}
pb.TSCTASKONLINECOLLECT.fields = {pb.TSCTASKONLINECOLLECTTASKONLINE_FIELD, pb.TSCTASKONLINECOLLECTTECHPOINT_FIELD, pb.TSCTASKONLINECOLLECTSTARDUST_FIELD}
pb.TSCTASKONLINECOLLECT.is_extendable = false
pb.TSCTASKONLINECOLLECT.extensions = {}
pb.TCSGUIDEGUIDE_FIELD.name = "guide"
pb.TCSGUIDEGUIDE_FIELD.full_name = ".com.nkm.common.proto.client.TCSGuide.guide"
pb.TCSGUIDEGUIDE_FIELD.number = 1
pb.TCSGUIDEGUIDE_FIELD.index = 0
pb.TCSGUIDEGUIDE_FIELD.label = 1
pb.TCSGUIDEGUIDE_FIELD.has_default_value = false
pb.TCSGUIDEGUIDE_FIELD.default_value = ""
pb.TCSGUIDEGUIDE_FIELD.type = 9
pb.TCSGUIDEGUIDE_FIELD.cpp_type = 9

pb.TCSGUIDE.name = "TCSGuide"
pb.TCSGUIDE.full_name = ".com.nkm.common.proto.client.TCSGuide"
pb.TCSGUIDE.nested_types = {}
pb.TCSGUIDE.enum_types = {}
pb.TCSGUIDE.fields = {pb.TCSGUIDEGUIDE_FIELD}
pb.TCSGUIDE.is_extendable = false
pb.TCSGUIDE.extensions = {}
pb.TCSUSERLEVELUP.name = "TCSUserLevelUp"
pb.TCSUSERLEVELUP.full_name = ".com.nkm.common.proto.client.TCSUserLevelUp"
pb.TCSUSERLEVELUP.nested_types = {}
pb.TCSUSERLEVELUP.enum_types = {}
pb.TCSUSERLEVELUP.fields = {}
pb.TCSUSERLEVELUP.is_extendable = false
pb.TCSUSERLEVELUP.extensions = {}
pb.TSCUSERLEVELUPLEVEL_FIELD.name = "level"
pb.TSCUSERLEVELUPLEVEL_FIELD.full_name = ".com.nkm.common.proto.client.TSCUserLevelUp.level"
pb.TSCUSERLEVELUPLEVEL_FIELD.number = 1
pb.TSCUSERLEVELUPLEVEL_FIELD.index = 0
pb.TSCUSERLEVELUPLEVEL_FIELD.label = 1
pb.TSCUSERLEVELUPLEVEL_FIELD.has_default_value = false
pb.TSCUSERLEVELUPLEVEL_FIELD.default_value = 0
pb.TSCUSERLEVELUPLEVEL_FIELD.type = 5
pb.TSCUSERLEVELUPLEVEL_FIELD.cpp_type = 1

pb.TSCUSERLEVELUP.name = "TSCUserLevelUp"
pb.TSCUSERLEVELUP.full_name = ".com.nkm.common.proto.client.TSCUserLevelUp"
pb.TSCUSERLEVELUP.nested_types = {}
pb.TSCUSERLEVELUP.enum_types = {}
pb.TSCUSERLEVELUP.fields = {pb.TSCUSERLEVELUPLEVEL_FIELD}
pb.TSCUSERLEVELUP.is_extendable = false
pb.TSCUSERLEVELUP.extensions = {}

TCSGuide = protobuf.Message(pb.TCSGUIDE)
TCSTaskOnlineCollect = protobuf.Message(pb.TCSTASKONLINECOLLECT)
TCSUserLevelUp = protobuf.Message(pb.TCSUSERLEVELUP)
TSCTaskOnlineCollect = protobuf.Message(pb.TSCTASKONLINECOLLECT)
TSCUserLevelUp = protobuf.Message(pb.TSCUSERLEVELUP)

